### ISSUE TITLE
Info update failed in payment section.

### ISSUE THREAD

**Issue by smarikachaudhary** [SwasthaniStha/Farmish#20]
When delivery option is updated in the checkout information section, it does not get updated in the billing information section.
![swasthani](https://github.com/SwasthaniStha/Farmish/assets/119168456/b2edeb4f-aeb5-4c7a-a1fc-ef5ab6aa1ff9)

**Comment by SwasthaniStha** [comment]
The error has been solved!
This error occurred because the delivery method was not being redirected to the next template which is billing information section. 
To solve that, changes were made and delivery method was called and redirected like other information of the shipping info form.
![image](https://github.com/SwasthaniStha/Farmish/assets/119651873/86294b31-3150-44fc-b6e7-2a97ea9acc68)
