### ISSUE TITLE
Shipping address update error!

### ISSUE THREAD

**Issue by smarikachaudhary** [SwasthaniStha/Farmish#25]
Failed to update shipping address of newly registered users.
![swasthani (1)](https://github.com/SwasthaniStha/Farmish/assets/119168456/395c2a37-1f33-4ec1-ae31-637229c15c4d)

**Comment by SwasthaniStha** [comment]
The error occurred while registering shipping address for new users. It was definitely because while creating shipping address form, the code did not account for newly registered users. 
It has been solved by having a code generate shipping model automatically when a new user creates an account.
![image](https://github.com/SwasthaniStha/Farmish/assets/119651873/7769217e-630a-4e50-aad0-5ceef77e04e8)
